# Optimized Cloud Build for Mafia Backend
steps:
  # Build and push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-f'
      - apps/backend/Dockerfile
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/mafia-backend:$BUILD_ID'
      - '-t'  
      - 'eu.gcr.io/$PROJECT_ID/mafia-backend:latest'
      - '.'
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'eu.gcr.io/$PROJECT_ID/mafia-backend:$BUILD_ID'
    id: 'push-versioned'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'eu.gcr.io/$PROJECT_ID/mafia-backend:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Deploy to Cloud Run with optimized settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - mafia-backend-prod
      - '--image=eu.gcr.io/$PROJECT_ID/mafia-backend:$BUILD_ID'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--platform=managed'
      
      # Performance optimizations (from their suggestion)
      - '--timeout=3600'
      - '--concurrency=200'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--cpu=1'
      - '--memory=1Gi'
      - '--no-cpu-throttling'
      - '--session-affinity'
      
      # VPC and security
      - '--vpc-connector=mafia-connector-eu'
      - '--vpc-egress=private-ranges-only'
      - '--service-account=mafia-backend@${PROJECT_ID}.iam.gserviceaccount.com'
      
      # Environment variables
      - '--set-env-vars=NODE_ENV=production,REDIS_URL=${_REDIS_URL},CORS_ORIGIN=${_CORS_ORIGIN}'
      
      # Labels
      - '--labels=env=production,app=mafia-backend'
    id: 'deploy-service'
    waitFor: ['push-versioned', 'push-latest']

  # Add public access permissions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - services
      - add-iam-policy-binding
      - mafia-backend-prod
      - '--region=europe-west1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'
    id: 'add-permissions'
    waitFor: ['deploy-service']

  # Health check (smoke test) with dynamic URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        SERVICE_URL=$$(gcloud run services describe mafia-backend-prod --region=europe-west1 --format="value(status.url)")
        echo "Testing health endpoint: $$SERVICE_URL/health"
        curl -f -s "$$SERVICE_URL/health" || exit 1
    id: 'smoke-test'
    waitFor: ['add-permissions']

# Substitutions (required)
substitutions:
  _REDIS_URL: 'redis://10.154.0.3:6379'  # Update with actual Redis IP
  _CORS_ORIGIN: 'https://your-app.vercel.app'  # Update with actual frontend URL

# Build options
options:
  logging: 'CLOUD_LOGGING_ONLY'
  machineType: 'E2_HIGHCPU_8'

# Tags
tags: ['mafia-backend', 'production', 'europe-west1']

# Timeout
timeout: '1800s'  # 30 minutes